import Head from 'next/head'
import EZButton from '../components/EZButton'
import EZNavbar from '../components/EZNavbar'
import style from '../styles/scss/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>EZ Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/EZ-icon.svg" />
      </Head>
      <EZNavbar />
      <header className={`${style.header} d-flex justify-content-center align-items-center`}>
        <div className="container content text-center">
          <h1 className='fw-bolder text-white fs-1'>
            Awesome App <br /> For Saving Time.
          </h1>
          <p className='text-white my-4'>
          We bring you a mobile app for banking problems that oftenly wasting much of your times.
          </p>
          <EZButton variant='white' className='px-lg-5 py-lg-3'>Try It Free</EZButton>
        </div>
      </header>
    </>
  )
}
